<a href="https://colab.research.google.com/github/niranjan-sa/DataScience/blob/master/Basics_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hi,
I'll be trying to maintain the basics of the Linear Algebra at one place, here in this notebook.   
Please feel free to add new concepts to this notebook.

# Measures of Magnitude
A list of most commonly used norms and their library function equivalents.   
Norm ? - a way of measuring things. (esp. distance travelled by a vector when it goes from one end to another...)  
Axioms of norms  

1.   They are non-negative (i.e.) ||v|| >= 0
2.   Distances multiply with scaler multiplication. (i.e.) if 'a' is a scaler and has to be multiplied to a vector 'v' then the norm would be |a| * ||v||. (even if a is negative, norm would be positive)
3.   (Triangle inequality) Please follow the image below.

      ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Vector_triangle_inequality.PNG/220px-Vector_triangle_inequality.PNG)


### Different Norms
Consider following vectors for example.

$\vec V =
 \begin{pmatrix}
  a_{1}  \\
  a_{2}  \\
  a_{3} 
 \end{pmatrix}$

1.   Euclidean Norm  
     The Euclidean Norm or L-2 norm of the vector is nothing but the following.   
    $ ||\vec V|| = \sqrt{a_1^2 + a_2^2+a_3^2}$
      In numpy using the norm function using 'default' parameters gives L2 norms.










In [0]:
## Euclidean Norm
import numpy as np

V = np.array((1,2,3))

In [36]:
V

array([1, 2, 3])

In [37]:
np.linalg.norm(V)

3.7416573867739413

Another interesting example (Two matrices same numbers but different shape)

In [0]:
## Creating vectors.
a = np.arange(9) - 2
b = a.reshape((3,3))

In [39]:
a

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [40]:
b

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [41]:
## Printing 2-norm or euclidean norm (They are exactly the same. Even if the shapes of the matrices are different.)
print (np.linalg.norm(a))
print (np.linalg.norm(b))

9.797958971132712
9.797958971132712


2.   L1 Norm
      $ ||\vec V|| = \sum_{i=0}^n |v_i|$ is also know as **Manhattan Norm or Taxi Cab Metric**    
        So for our vectors a and b, the L-1 norm looks like this.



In [42]:
print (a)
np.linalg.norm(a, ord = 1)

[-2 -1  0  1  2  3  4  5  6]


24.0

3.  $||V||_\infty$ Norm is nothing but the approximately the max element in the given array.  
  Therefore $||V||_\infty = max_i |v_i|$  
  

In [43]:
print (a)

[-2 -1  0  1  2  3  4  5  6]


In [44]:
np.linalg.norm(a, ord=np.Inf)

6.0

Acknowledgements - 

Numpy docs  
Json Brown Lee